# ---- Development Stage ----
FROM node:20-alpine3.16 AS development
WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci
RUN npx prisma generate

COPY . .

CMD ["npm", "run", "start:dev"]

# ---- Builder Stage ----
FROM node:20-alpine3.16 AS builder
WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma/schema.prisma ./prisma/

RUN npm ci

COPY . .

RUN npx prisma generate
RUN npm run build


# ---- Production Stage ----
FROM node:20-alpine3.16 AS production
WORKDIR /usr/src/app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev && npm cache clean --force

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /usr/src/app/prisma/ ./prisma/
COPY --from=builder /usr/src/app/doc ./doc/

CMD ["npm", "run", "start:prod"]
