services:
  app-prod:
    build:
      dockerfile: Dockerfile-app
      context: .
      target: production
    container_name: nodejs_app_prod
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: always
    command: npm run start:prod
    networks:
      - app-network
    profiles:
      - prod

  app-dev:
    build:
      dockerfile: Dockerfile-app
      context: .
      target: development
    container_name: nodejs_app_dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    restart: always
    command: npm run start:dev
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - app-network
    profiles:
      - dev

  postgres:
    build:
      dockerfile: Dockerfile-db
      context: .
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - app-network

volumes:
  postgres_data:
  postgres_logs:

networks:
  app-network:
    driver: bridge